name: Image Build Runc
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    container: rancher/hardened-build-base:v1.21.7b1
    steps:
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: refs/tags/${{ github.ref_name }}
    - name: Build
      run: make GH_TAG=${{ github.ref_name }}
    - name: Scan
      run: make GH_TAG=${{ github.ref_name }} image-scan
    - name: Publish
      run: make GH_TAG=${{ github.ref_name }} image-push
