name: Image Build Runc
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: rancher/hardened-build-base:v1.21.b1
    steps:
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: make GH_TAG=${{ github.ref_name }}
    - name: Scan
      run: make GH_TAG=${{ github.ref_name }} image-scan
    - name: Publish
      run: make GH_TAG=${{ github.ref_name }} image-push
